### ISSUE TITLE
error when run 'python train.py --config ./configs/train_desc.yaml'

### ISSUE THREAD

**Issue by guijuzhejiang** [The-Learning-And-Vision-Atelier-LAVA/PoSFeat#4]
]
total number of image pairs loaded: 788921
descriptor/descriptor 1/10:   0%|                     | 0/10000 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/swordwu/workspace/PoSFeat/train.py", line 9, in <module>
    trainer.train()
  File "/home/swordwu/workspace/PoSFeat/managers/trainer.py", line 290, in train
    self.val_and_vis(batch_path_list, idx)
  File "/home/swordwu/miniconda3/envs/nerf_py39/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/swordwu/workspace/PoSFeat/managers/trainer.py", line 499, in val_and_vis
    cv2.circle(comb_img_kps, kp1, radius=2, color=color, thickness=-1)
cv2.error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'circle'
> Overload resolution failed:
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type

**Comment by KunB-Fighting** [comment]
this is an error about opencv, you can try to transform the data type of kp1, just like the code in line 501 (current error is in line 499)

**Comment by atharvjairath** [comment]
@KunB-Fighting 
I fixed the above issue by using `kp1_comb = (int(kp1[0]+w+mid_pad), int(kp1[1]))` instead of kp1 in trainer.py

After doing that, the above error was fixed but it gave me a new following error:
```
line 1225, in _process_data
    data.reraise()
  File "/mnt/private/atharv/anaconda3/envs/posfeat/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/mnt/private/atharv/anaconda3/envs/posfeat/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/private/atharv/anaconda3/envs/posfeat/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/mnt/private/atharv/hyperturing/posfeat/PoSFeat/managers/trainer.py", line 151, in my_collate
    return torch.utils.data.dataloader.default_collate(batch)
  File "/mnt/private/atharv/anaconda3/envs/posfeat/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 45, in default_collate
    elem = batch[0]
IndexError: list index out of range
```

not sure why batch[0] is out of index
